sonar.organization=prashant2781
sonar.projectKey=prashant2781_insurance-claim-devsecops
sonar.projectName=Insurance Claim DevSecOps

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,.venv/**,htmlcov/**,.pytest_cache/**,.ruff_cache/**
sonar.coverage.exclusions=tests/**
